### ISSUE TITLE
Slideshow Freezing

### ISSUE THREAD

**Issue by rdmustang** [ubershmekel/redditp#49] opened 2016-02-17 18:52 UTC
New user to redditp but I'm already a huge fan. I noticed that the slideshow freezes when the next image is a video. I can manually flip to the next image and the slideshow starts up again. I am experiencing this in Chrome and Firefox. Any way to fix this? Thanks!

**Comment by ubershmekel** [comment] 2016-02-17 19:39
This may be an issue caused by the preloading.

Can you share a link where this happens? Or just a subreddit? I need to be able to reproduce the issue.

**Comment by rdmustang** [comment] 2016-02-17 20:02
It doesn't happen every time but it is happening at least every few minutes for me. 

It's currently happening using http://redditp.com/r/gaming

**Comment by Hrxn** [comment] 2016-02-17 21:43
But manual progress (space, right arrow, etc.) *always* works?

I think I know what you mean, but I can't reproduce it reliably. Restarting the slide-show by pressing 'a' twice (or clicking that auto-next checkbox) also makes it start up again for you?

I guess this has something to do with trying to preload/precache data and then running into network latency issues or something like that. Because it is not restricted to videos, at least for me. I just landed on a simple image, and the slideshow stopped, or froze, as you said it.
I also tried it on http://redditp.com/r/gaming

Maybe try it on an image-only subreddit, like r/pics/ or whatever, just to be sure.

**Comment by rdmustang** [comment] 2016-02-17 22:40
I re-read open issues and this issue appears to be the same as issue #48. I apologize for opening a duplicate issue.

**Comment by rdmustang** [comment] 2016-02-17 22:43
I found someone else who might be having the same issue. Link:

https://www.reddit.com/r/redditp/comments/462wtg/redditp_does_not_preload_the_entire_slideshow

[–]Lolizard123 1 point 6 hours ago 
It can load past 25 images again on surface rt. The only issue is now when a gif is ahead of an image in the queue ie. Image 1 is a picture and image 2 is a gif. Auto-next set to 1 second and it won't continue to the gif. Appears to actually be gfycat hosted stuff instead of gif.

**Comment by ubershmekel** [comment] 2016-02-18 02:35
I believe I have the fix live now.
https://github.com/ubershmekel/redditp/commit/849d8e53cc23a69e0f2d010f2f00e05c0a07d97b

Let me know if this solves the issue for you as well. It was the preloading of gifs that botched the timer for the currently visible image.

**Comment by Hrxn** [comment] 2016-02-18 04:20
Looks good, just watched a slideshow of r/gaming up to 105, and wasn't stuck once

**Comment by rdmustang** [comment] 2016-02-18 15:25
Works well here too. Thank you! Now I just get the occasional AJAX error but that's a lot better than the slideshow freezing every 5th picture.

**Comment by ubershmekel** [comment] 2016-02-18 17:46
Thank you all for the report and the testing. @rdmustang if you have a way to reproduce or more information on the error - please do open a new issue.

**Closed by ubershmekel** 2016-02-18 17:46 UTC
