### ISSUE TITLE
Infinite loop loading the site

### ISSUE THREAD

**Issue by Foxandxss** [ubershmekel/redditp#133] opened 2021-11-03 09:22 UTC
Coming from #132 

I came here to find someone with the same issue and I am not the only one

![image](https://user-images.githubusercontent.com/1087957/140035279-93872732-0219-400c-b91a-3f24192ecea7.png)

Cannot load any page but old.redditp es working nicely.

I am from Spain using Movistar as ISP (it is the biggest one).

**Comment by auktis** [comment] 2021-11-03 21:05
Yep, exact same problem here in France.
When I use Tor Browser or if I open `www.redditp.com` on my mobile phone, with another ISP, **it works well**.
So it seems the problem is linked to the source of client requests.

Yet, `old.redditp.com` works fine. How does that make any sense?

**Comment by ubershmekel** [comment] 2021-11-04 03:38
Gosh this is odd. I suspect netlify is a suboptimal host. I'll try and debug more soon. Please dump as much operating system, country of origin, and HTTPS cert information as possible in this thread. I'm testing stuff out at http://gh.redditp.com

**Comment by Foxandxss** [comment] 2021-11-04 08:11
Both `gh.` and the main one works again for me. Could be a temporary netlify issue. Is it good for you @auktis ?

**Comment by auktis** [comment] 2021-11-04 19:24
Well… The problem is gone! 🤷‍♂️

**Comment by ubershmekel** [comment] 2021-11-04 20:31
Great. I'll close this issue for now. Please re-open if it happens again. I should advertise gh.redditp.com and old.redditp.com somewhere as workarounds.

**Closed by ubershmekel** 2021-11-04 20:31 UTC
